"""
Moderator FAQ System Data Structure

This module contains structured FAQ data for the moderator help system,
extracted from the hardcoded if/elif chain in the main bot file.
"""

# FAQ Data Structure: Each entry contains patterns and response data
FAQ_DATA = {"strikes": {"patterns": ["explain strikes",
                                     "strike",
                                     "strike system"],
                        "title": "📋 **Strike Management System Analysis**",
                        "sections": [{"title": "Purpose",
                                      "content": "Automatic strike tracking with manual moderation controls. I monitor the violation channel and add strikes when users are mentioned.",
                                      },
                                     {"title": "Automatic Detection",
                                      "content": ["• **Channel:** <#{VIOLATION_CHANNEL_ID}> (VIOLATION_CHANNEL_ID)",
                                                  "• When users are @mentioned in this channel, I automatically add strikes",
                                                  "• Captain Jonesy cannot receive strikes (protection protocol)",
                                                  "• I send notifications to mod alert channel for each strike added",
                                                  ],
                                      },
                                     {"title": "Manual Commands",
                                      "content": ["• `!strikes @user` — Query user's current strike count",
                                                  "• `!resetstrikes @user` — Reset user strikes to zero",
                                                  "• `!allstrikes` — Display comprehensive strike report",
                                                  ],
                                      },
                                     {"title": "Database",
                                      "content": "PostgreSQL with persistence across restarts. Individual queries work as fallback if bulk operations fail.",
                                      },
                                     {"title": "Security",
                                      "content": "Only users with 'Manage Messages' permission can use manual strike commands.",
                                      },
                                     ],
                        },
            "members": {"patterns": ["explain members",
                                     "member",
                                     "member system"],
                        "title": "👥 **Member Interaction System Analysis**",
                        "sections": [{"title": "Purpose",
                                      "content": "Special privileges for YouTube Members with conversation tracking and tier-based responses.",
                                      },
                                     {"title": "Member Role IDs",
                                      "content": ["• YouTube Member: Space Cat (1018908116957548666)",
                                                  "• YouTube Member (1018908116957548665)",
                                                  "• YouTube Member: Space Cat duplicate (1127604917146763424)",
                                                  "• Space Ocelot (879344337576685598)",
                                                  ],
                                      },
                                     {"title": "Conversation System",
                                      "content": ["• **Unlimited** conversations in Senior Officers' Area (<#{MEMBERS_CHANNEL_ID}>)",
                                                  "• **5 daily responses** in other channels, then encouraged to move to members area",
                                                  "• **Daily reset** at midnight (conversation counts reset automatically)",
                                                  "• Enhanced AI responses with more engagement than standard users",
                                                  ],
                                      },
                                     {"title": "User Hierarchy",
                                      "content": "Captain Jonesy → Sir Decent Jam → Moderators → Members → Standard Users",
                                      },
                                     {"title": "Edge Cases",
                                      "content": "Users with both moderator permissions AND member roles are classified as 'moderator' tier (higher privilege takes precedence).",
                                      },
                                     ],
                        },
            "database": {"patterns": ["explain database",
                                      "played games",
                                      "game database"],
                         "title": "🎮 **Played Games Database System Analysis**",
                         "sections": [{"title": "Purpose",
                                       "content": "Comprehensive gaming history with metadata, statistics, and AI-powered natural language queries.",
                                       },
                                      {"title": "Key Features",
                                       "content": ["• **15+ metadata fields** per game (genre, series, platform, completion status, etc.)",
                                                   "• **Array support** for alternative names and Twitch VOD URLs",
                                                   "• **AI enhancement** for automatic genre/series detection",
                                                   "• **Statistical analysis** for gaming insights and rankings",
                                                   ],
                                       },
                                      {"title": "Management Commands",
                                       "content": ["• `!addplayedgame <name> | series:Series | year:2023 | status:completed | episodes:12`",
                                                   "• `!listplayedgames [series]` — List games, optionally filtered by series",
                                                   "• `!gameinfo <name_or_id>` — Detailed game information",
                                                   "• `!updateplayedgame <name_or_id> status:completed | episodes:15`",
                                                   ],
                                       },
                                      {"title": "Import System",
                                       "content": ["• `!bulkimportplayedgames` — YouTube playlists + Twitch VODs with real playtime",
                                                   "• `!updateplayedgames` — AI metadata enhancement for existing games",
                                                   "• `!cleanplayedgames` — Remove already-played games from recommendations",
                                                   ],
                                       },
                                      {"title": "Natural Language Queries",
                                       "content": "Users can ask 'Has Jonesy played [game]?' and get intelligent responses with follow-up suggestions.",
                                       },
                                      ],
                         },
            "commands": {"patterns": ["explain commands",
                                      "command",
                                      "bot commands",
                                      "what can you do",
                                      "capabilities"],
                         "title": "⚙️ **Bot Command System Analysis**",
                         "sections": [{"title": "Architecture",
                                       "content": "Event-driven command processing with permission-based access control.",
                                       },
                                      {"title": "User Commands (Everyone)",
                                       "content": ["• `!addgame <name> - <reason>` / `!recommend <name> - <reason>` — Add game recommendation",
                                                   "• `!listgames` — View all game recommendations",
                                                   "• **Trivia Tuesday Participation:** Answer questions during weekly trivia sessions (no commands needed - just respond when trivia is active)",
                                                   ],
                                       },
                                      {"title": "Moderator Commands (Manage Messages required)",
                                       "content": ["• **Strike Management:** `!strikes`, `!resetstrikes`, `!allstrikes`",
                                                   "• **Game Management:** `!removegame`, `!addplayedgame`, `!updateplayedgame`",
                                                   "• **Database Operations:** `!bulkimportplayedgames`, `!cleanplayedgames`",
                                                   "• **Reminder System:** `!remind`, `!listreminders`, `!cancelreminder`",
                                                   "• **Trivia Management:** `!addtrivia`, `!starttrivia`, `!endtrivia`, `!trivialeaderboard`, `!listpendingquestions`, `!disabletrivia`, `!enabletrivia`, `!triviahelp`, `!resettrivia`",
                                                   "• **Trivia Quality Control:** `!approvequestion`, `!approvestatus`, `!addtriviaquestion`",
                                                   "• **AI Configuration:** `!setpersona`, `!toggleai`, `!ashstatus`",
                                                   ],
                                       },
                                      {"title": "Elite Access (Captain Jonesy & Sir Decent Jam)",
                                       "content": ["• **Announcement System:** `!announce`, `!scheduleannouncement`, `!emergency`",
                                                   "• **Special Authority:** Full access to all bot systems and overrides",
                                                   ],
                                       },
                                      {"title": "Natural Language Processing",
                                       "content": ["• Statistical queries: 'What game series has the most playtime?'",
                                                   "• Game lookups: 'Has Jonesy played God of War?'",
                                                   "• Genre queries: 'What horror games has Jonesy played?'",
                                                   ],
                                       },
                                      {"title": "Weekly Events",
                                       "content": ["• **Trivia Tuesday:** Weekly community trivia with gaming questions",
                                                   "• **Sunday Updates:** Automatic game database updates at 12:00 PM UK time",
                                                   "• **Member Conversations:** Enhanced AI responses for YouTube Members",
                                                   ],
                                       },
                                      {"title": "Permission System",
                                       "content": "Commands check user roles and guild permissions before execution. Captain Jonesy and Sir Decent Jam have elevated access for announcements.",
                                       },
                                      ],
                         },
            "ai": {"patterns": ["explain ai",
                                "artificial intelligence",
                                "ai system"],
                   "title": "🧠 **AI Integration System Analysis**",
                   "sections": [{"title": "Dual AI Architecture",
                                 "content": ["• **Primary:** Google Gemini 1.5 Flash (fast, efficient)",
                                             "• **Backup:** Claude 3 Haiku (fallback if Gemini fails)",
                                             "• **Automatic failover** with quota monitoring",
                                             ],
                                 },
                                {"title": "Personality System",
                                 "content": ["• **Character:** Science Officer Ash from Alien (1979)",
                                             "• **Configurable:** `!setpersona` to modify personality",
                                             "• **Response filtering** to prevent repetitive character phrases",
                                             "• **Tier-aware** responses based on user authority level",
                                             ],
                                 },
                                {"title": "AI Features",
                                 "content": ["• **Game metadata enhancement** (genre, series, release year detection)",
                                             "• **Natural language query processing** for gaming statistics",
                                             "• **Conversation management** with context awareness",
                                             "• **Error handling** with graceful fallbacks to static responses",
                                             ],
                                 },
                                {"title": "Configuration",
                                 "content": ["• Current Status: {ai_status_message}",
                                             "• Toggle with `!toggleai` command",
                                             "• Rate limiting prevents quota exhaustion",
                                             ],
                                 },
                                ],
                   },
            "tiers": {"patterns": ["explain tiers",
                                   "user tier",
                                   "user system"],
                      "title": "👑 **User Tier System Analysis**",
                      "sections": [{"title": "Hierarchy (Highest to Lowest)",
                                    "content": ""},
                                   {"title": "1. Captain Jonesy (ID: {JONESY_USER_ID})",
                                    "content": ["• Addressed as 'Captain' with military courtesy",
                                                "• Cannot receive strikes (protection protocol)",
                                                "• Unlimited conversation access everywhere",
                                                ],
                                    },
                                   {"title": "2. Sir Decent Jam (ID: {JAM_USER_ID})",
                                    "content": ["• Acknowledged as bot creator with special respect",
                                                "• Full command access, development privileges",
                                                ],
                                    },
                                   {"title": "3. Moderators (Manage Messages Permission)",
                                    "content": ["• Professional courtesy and authority recognition",
                                                "• Full moderator command suite, unlimited conversations",
                                                "• Access to detailed FAQ system (this system)",
                                                ],
                                    },
                                   {"title": "4. Members (YouTube Member Roles)",
                                    "content": ["• Enhanced conversations, more engaging responses",
                                                "• Unlimited in Senior Officers' Area (<#{MEMBERS_CHANNEL_ID}>)",
                                                "• 5 daily responses in other channels",
                                                ],
                                    },
                                   {"title": "5. Standard Users",
                                    "content": ["• Basic bot interactions, public commands",
                                                "• Can ask natural language questions about games",
                                                ],
                                    },
                                   {"title": "Detection Logic",
                                    "content": "`get_user_communication_tier()` checks in hierarchy order. Higher tiers take precedence over lower ones.",
                                    },
                                   ],
                      },
            "import": {"patterns": ["explain import",
                                    "import system",
                                    "bulk import"],
                       "title": "📥 **Game Import System Analysis**",
                       "sections": [{"title": "Purpose",
                                     "content": "Automated import of gaming history from YouTube and Twitch with comprehensive metadata.",
                                     },
                                    {"title": "Import Sources",
                                     "content": ["• **YouTube:** Playlist-based detection with accurate video duration calculation",
                                                 "• **Twitch:** VOD analysis with duration tracking and series grouping",
                                                 "• **AI Enhancement:** Automatic genre, series, and release year detection",
                                                 ],
                                     },
                                    {"title": "Commands",
                                     "content": ["• `!bulkimportplayedgames` — Full import from APIs with AI metadata",
                                                 "• `!updateplayedgames` — AI enhancement for existing games",
                                                 "• `!cleanplayedgames` — Remove already-played games from recommendations",
                                                 ],
                                     },
                                    {"title": "Data Processing",
                                     "content": ["• **Smart Deduplication:** Merges YouTube + Twitch data for same games",
                                                 "• **Completion Detection:** Automatically identifies completed vs ongoing series",
                                                 "• **Alternative Names:** Generates searchable aliases (RE2, GoW 2018, etc.)",
                                                 "• **Real Playtime:** Calculates actual time from video durations, not estimates",
                                                 ],
                                     },
                                    {"title": "API Requirements",
                                     "content": "YouTube Data API key, Twitch Client ID/Secret (optional but recommended).",
                                     },
                                    ],
                       },
            "statistics": {"patterns": ["explain statistics",
                                        "stats",
                                        "analytics"],
                           "title": "📊 **Statistical Analysis System**",
                           "sections": [{"title": "Purpose",
                                         "content": "Advanced gaming analytics with natural language query processing and intelligent follow-up suggestions.",
                                         },
                                        {"title": "Query Types",
                                         "content": ["• **Playtime Analysis:** 'What game series has the most playtime?'",
                                                     "• **Episode Rankings:** 'Which game has the most episodes?'",
                                                     "• **Completion Metrics:** 'What game took longest to complete?'",
                                                     "• **Efficiency Analysis:** 'What game has highest average playtime per episode?'",
                                                     ],
                                         },
                                        {"title": "Database Functions",
                                         "content": ["• `get_series_by_total_playtime()` — Series playtime rankings",
                                                     "• `get_longest_completion_games()` — Completion time analysis",
                                                     "• `get_games_by_episode_count()` — Episode count statistics",
                                                     "• `get_games_by_average_episode_length()` — Efficiency metrics",
                                                     ],
                                         },
                                        {"title": "Enhanced Responses",
                                         "content": ["• **Contextual Follow-ups:** Suggests related queries based on results",
                                                     "• **Comparative Analysis:** Shows rankings and differences between games",
                                                     "• **Series Insights:** Analyzes franchise-level gaming patterns",
                                                     ],
                                         },
                                        {"title": "Processing",
                                         "content": "Pattern matching identifies query type, routes to appropriate database function, generates response with Ash personality.",
                                         },
                                        ],
                           },
            "scheduled": {"patterns": ["explain scheduled",
                                       "automatic update",
                                       "schedule"],
                          "title": "⏰ **Scheduled Update System Analysis**",
                          "sections": [{"title": "Schedule",
                                        "content": "Every Sunday at 12:00 PM (midday) UTC"},
                                       {"title": "Purpose",
                                        "content": "Automatically update ongoing games with fresh metadata from YouTube API."},
                                       {"title": "Update Process",
                                        "content": ["• **Target Games:** Only games with 'ongoing' completion status",
                                                    "• **Data Sources:** YouTube playlists for episode count and playtime",
                                                    "• **Change Detection:** Only updates games where data has actually changed",
                                                    "• **Preservation:** Maintains manually edited information",
                                                    ],
                                        },
                                       {"title": "Update Logic",
                                        "content": ["1. Query database for ongoing games with YouTube playlist URLs",
                                                    "2. Fetch current playlist metadata via YouTube API",
                                                    "3. Compare episode counts - update only if changed",
                                                    "4. Recalculate playtime from actual video durations",
                                                    "5. Update database records with new metadata",
                                                    ],
                                        },
                                       {"title": "Notifications",
                                        "content": "Status reports sent to <#{MOD_ALERT_CHANNEL_ID}>"},
                                       {"title": "Implementation",
                                        "content": "`@tasks.loop(time=time(12, 0))` decorator with `scheduled_games_update()` function. Includes error handling and rate limiting.",
                                        },
                                       ],
                          },
            "recommendations": {"patterns": ["explain recommendations",
                                             "game rec",
                                             "rec system"],
                                "title": "🎯 **Game Recommendations System Analysis**",
                                "sections": [{"title": "Purpose",
                                              "content": "Community-driven game suggestion system with persistent list management."},
                                             {"title": "User Commands",
                                              "content": ["• `!addgame <name> - <reason>` / `!recommend <name> - <reason>`",
                                                          "• `!listgames` — View all recommendations with contributor info",
                                                          ],
                                              },
                                             {"title": "Moderator Commands",
                                              "content": ["• `!removegame <name_or_index>` — Remove recommendation by name or index",
                                                          "• `!cleanplayedgames` — Remove already-played games from recommendations",
                                                          ],
                                              },
                                             {"title": "Database Features",
                                              "content": ["• **Duplicate Detection:** Fuzzy matching prevents duplicate entries",
                                                          "• **Contributor Tracking:** Records who suggested each game",
                                                          "• **Persistent Storage:** PostgreSQL with automatic indexing",
                                                          ],
                                              },
                                             {"title": "Smart Features",
                                              "content": ["• **Auto-Update Channel:** Persistent list in recommendations channel",
                                                          "• **Typo Tolerance:** Fuzzy matching for game name recognition",
                                                          "• **Batch Processing:** Can add multiple games in one command",
                                                          "• **API Integration:** Cross-reference with played games to avoid duplicates",
                                                          ],
                                              },
                                             {"title": "Special Handling",
                                              "content": "Sir Decent Jam's contributions don't show contributor names (configured via user ID check).",
                                              },
                                             ],
                                },
            "reminders": {"patterns": ["explain reminders",
                                       "reminder system",
                                       "remind"],
                          "title": "⏰ **Reminder System**",
                          "sections": [{"title": "Purpose",
                                        "content": "A versatile system for setting **personal reminders** (available to all users) and scheduling powerful **channel announcements** (a moderator tool)."},
                                       {"title": "✅ For All Users: Personal Reminders",
                                        "content": ["Any user can set a personal reminder using natural language. The bot will send you a Direct Message (DM) when the time comes.",
                                                    "• `remind me in 10 minutes to check the server`",
                                                    "• `remind me at 8pm to watch the stream`",
                                                    "• `remind me tomorrow at noon`"]},
                                       {"title": "🔒 For Moderators: Advanced Features",
                                        "content": "Moderators with `Manage Messages` permissions can remind other users and schedule announcements for the entire channel."},
                                       {"title": "Moderator Command Examples",
                                        "content": ["• `!remind @user 2h to check on your report` — Sends a DM reminder to a specific user.",
                                                    "• `!remind everyone in this channel at 17:00 meeting starts soon!` — Pings everyone in the current channel.",
                                                    "• `!remind @here in 15m that Q&A is beginning!` — Pings only online members in the current channel.",
                                                    "• `!remind @RoleName 1d to submit your feedback` — Pings a specific, mentionable role."]},
                                       {"title": "Supported Time Formats",
                                        "content": ["• **Natural Language:** `in 5 minutes`, `10m`, `2 hours`, `1h`, `tomorrow at noon`, `next Tuesday at 8pm`",
                                                    "• **Clock Time:** `5pm`, `17:30`, `16.45`",
                                                    "• **Relative:** `1d 2h 30m` (days, hours, minutes combined)"]},
                                       {"title": "Auto-Action System (Moderator Only)",
                                        "content": ["Auto-actions can be attached to reminders set for a specific user.",
                                                    "• `... | auto:mute` — Mutes the user if no mod responds after the reminder.",
                                                    "• `... | auto:kick` — Kicks the user.",
                                                    "• `... | auto:ban` — Bans the user.",
                                                    "• **Note:** Any moderator message in the channel after the reminder is delivered will cancel the pending auto-action."]},
                                       {"title": "Other Commands",
                                        "content": ["• `!listreminders [@user]` — Shows your pending reminders (or a specific user's if you are a mod).",
                                                    "• `!cancelreminder <id>` — Cancels a reminder by its ID."]}]},
            "trivia": {"patterns": ["explain trivia",
                                    "trivia tuesday",
                                    "trivia system"],
                       "title": "🧠 **Trivia Tuesday System Analysis**",
                       "sections": [{"title": "Purpose",
                                     "content": "Weekly community trivia events with comprehensive question management and participation tracking.",
                                     },
                                    {"title": "Question Management (Moderators)",
                                     "content": ["• `!addtrivia <question> | answer:<correct_answer> | type:single` — Add single answer question",
                                                 "• `!addtrivia <question> | answer:<correct_answer> | choices:A,B,C,D | type:multiple` — Add multiple choice",
                                                 "• `!addtriviaquestion` — Start interactive DM conversation for question submission",
                                                 "• `!listpendingquestions` — View submitted questions awaiting use",
                                                 "• `!resettrivia` — Reset answered questions to available (bulk operation)",
                                                 ],
                                     },
                                    {"title": "Quality Control System",
                                     "content": ["• `!approvequestion <id>` — Send specific question to JAM for manual approval",
                                                 "• `!approvequestion auto` — Send next auto-selected question for approval",
                                                 "• `!approvequestion generate` — Generate new AI question and send for approval",
                                                 "• `!approvestatus` — Check status of pending JAM approvals",
                                                 "• **Approval Workflow:** JAM receives DM with options to approve, modify, or reject",
                                                 "• **24-hour timeout:** Approval conversations auto-expire for system cleanup",
                                                 ],
                                     },
                                    {"title": "Session Management (Moderators)",
                                     "content": ["• `!starttrivia [question_id]` — Start weekly trivia (auto-selects next question if no ID)",
                                                 "• `!endtrivia` — End current session and reveal results",
                                                 "• `!disabletrivia` — Disable scheduled Tuesday trivia (for special events/manual override)",
                                                 "• `!enabletrivia` — Re-enable scheduled Tuesday trivia automation",
                                                 "• `!trivialeaderboard` — Show participation and success statistics",
                                                 "• `!triviahelp` — Display complete trivia command reference",
                                                 ],
                                     },
                                    {"title": "Question Prioritization System",
                                     "content": ["• **Priority 1:** Recent mod-submitted questions (unused within 4 weeks)",
                                                 "• **Priority 2:** AI-generated questions focusing on statistical anomalies",
                                                 "• **Priority 3:** Any unused questions with 'available' status",
                                                 ],
                                     },
                                    {"title": "User Participation",
                                     "content": ["• Users submit answers during active trivia sessions",
                                                 "• **Conflict Detection:** Prevents mods from answering their own questions",
                                                 "• **First Correct Tracking:** Special recognition for fastest correct answer",
                                                 "• **Statistics:** Individual and community participation metrics",
                                                 ],
                                     },
                                    {"title": "Database Schema",
                                     "content": ["• **trivia_questions:** Question bank with metadata and usage tracking",
                                                 "• **trivia_sessions:** Active sessions with participant counts and results",
                                                 "• **trivia_answers:** Individual responses with correctness and timing",
                                                 "• **Status Tracking:** available → answered → (can be reset to available)",
                                                 ],
                                     },
                                    {"title": "Dynamic Questions",
                                     "content": "Support for questions with real-time calculated answers (e.g., 'What game currently has the most episodes?') with automatic answer computation at session start.",
                                     },
                                    ],
                       },
            "announcements": {"patterns": ["explain announcements",
                                           "explain announcement system",
                                           "how do announcements work",
                                           "announcement system analysis",
                                           "tell me about announcements"],
                              "title": "📢 **Announcement System Analysis**",
                              "sections": [{"title": "Purpose",
                                            "content": "High-priority communication system for server-wide announcements with special formatting and delivery.",
                                            },
                                           {"title": "Access Control",
                                            "content": ["• **Captain Jonesy Only:** Server owner has full announcement privileges",
                                                        "• **Sir Decent Jam Only:** Bot creator has full announcement access",
                                                        "• **Restriction Reason:** Prevents announcement spam and maintains authority hierarchy",
                                                        ],
                                            },
                                           {"title": "Command Types",
                                            "content": ["• `!announce <message>` — Standard announcement with special embed formatting",
                                                        "• `!scheduleannouncement <time> <message>` — Schedule announcement for future delivery",
                                                        "• `!emergency <message>` — Emergency announcement with @everyone ping",
                                                        ],
                                            },
                                           {"title": "Features",
                                            "content": ["• **Special Formatting:** Custom embed styling with authority indicators",
                                                        "• **Cross-posting:** Automatic delivery to multiple channels",
                                                        "• **Timestamp Logging:** Database tracking of announcement history",
                                                        "• **Priority Delivery:** Bypasses normal message rate limiting",
                                                        ],
                                            },
                                           {"title": "Delivery Channels",
                                            "content": ["• **Primary:** Main announcement channel",
                                                        "• **Secondary:** General discussion channels",
                                                        "• **Optional:** Member-specific channels based on announcement type",
                                                        ],
                                            },
                                           {"title": "Emergency System",
                                            "content": ["• **@everyone ping** for critical server announcements",
                                                        "• **Immediate delivery** without scheduling delays",
                                                        "• **Special visual formatting** to distinguish from regular announcements",
                                                        "• **Audit logging** for security and accountability",
                                                        ],
                                            },
                                           {"title": "Scheduling",
                                            "content": "Time format support matches reminder system: relative times (1h, 30m) and absolute timestamps (YYYY-MM-DD HH:MM).",
                                            },
                                           ],
                              },
            }
