import sys
import re

with open(r'bot\handlers\trivia\generator.py', 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Update TRIVIA_CATEGORIES
categories_pattern = re.compile(r"        TRIVIA_CATEGORIES = \{\n            # --- Channel stats \(factual, answer-first\) ---\n            'Episode_Champion': \{'weight': 2\.0\},.*?# --- AI-creative \(low weight - occasional variety\) ---\n            'Franchise_Lore': \{'weight': 0\.5\},  # Lore question, AI provides answer\n        \}", re.DOTALL)

new_categories = """        TRIVIA_CATEGORIES = {
            # --- Channel stats (factual, answer-first) ---
            'Episode_Champion': {'weight': 2.0},  # Most episodes in a genre
            'Quickest_Completion': {'weight': 1.5},  # Fewest episodes to finish in a genre
            'Channel_Timeline': {'weight': 2.0},  # Which game Jonesy played first
            'Genre_Census': {'weight': 1.5},  # How many games of a genre
            'Genre_Pioneer': {'weight': 1.5},  # First game in a genre by play date
            'Series_Comparison': {'weight': 1.5},  # Which series game had most episodes
            'Series_Total_Episodes': {'weight': 1.5},  # Total episodes across a whole franchise
            'Playtime_Battle': {'weight': 1.5},  # Which of 2 games has more playtime hours
            'Release_Year': {'weight': 1.5},  # What year was a specific game released?
            # Most YouTube views (YouTube-only, reduced weight to prevent repetition)
            'YouTube_Views_Champ': {'weight': 0.2},
            # --- AI-creative & Clips (moderate weight for variety) ---
            'Franchise_Lore': {'weight': 0.5},  # Lore question, AI provides answer
            'Clip_Famous_Last_Words': {'weight': 1.0},
            'Clip_Vibe_Check': {'weight': 1.0},
            'Clip_Cause_And_Effect': {'weight': 1.0},
        }"""

content = categories_pattern.sub(new_categories, content)

# 2. Add clip logic right before the Franchise_Lore elif
franchise_lore_pattern = re.compile(r"            elif cat == 'Franchise_Lore':")

clip_logic = """            elif cat == 'Clip_Famous_Last_Words':
                clips = current_db.trivia.get_random_clip_lore(limit=10, required_fields=['notable_quote', 'clip_outcome'])
                clips = [c for c in clips if c['clip_outcome'].lower() in ('death', 'failure')]
                if not clips:
                    print("⚠️ TRIVIA DIRECTOR: Not enough death/failure clips for Clip_Famous_Last_Words")
                    continue
                clip = random.choice(clips)
                correct_answer = None
                is_json_response = True
                print(f"✅ TRIVIA DIRECTOR: Got clip '{clip['trigger']}' for Clip_Famous_Last_Words")
                
                category_prompt = f\"\"\"Write one multiple-choice trivia question for fans of Captain Jonesy's gaming channel.
Jonesy uses she/her pronouns.

REAL CLIP DATA:
Game: {clip['game_title']}
Trigger: {clip['trigger']}
Outcome: {clip['clip_outcome']}
Quote spoken by Jonesy right before the outcome: "{clip['notable_quote']}"

Create a "Famous Last Words" style question. Example: "Right before falling off the map in Elden Ring, what did Jonesy confidently tell the chat?" or "Which boss was Jonesy fighting when she yelled [Quote] right before a Game Over?"
The correct answer must be the quote OR the game/boss depending on how you phrase it.
Provide 3 believable but incorrect decoy options.
Return strictly as JSON: {{"question_text": "...", "correct_answer": "...", "decoy_1": "...", "decoy_2": "...", "decoy_3": "...", "explanation": "Brief explanation."}}\"\"\"
                selected_category = cat

            elif cat == 'Clip_Vibe_Check':
                clips = current_db.trivia.get_random_clip_lore(limit=10, required_fields=['emotion_category', 'game_title'])
                if not clips:
                    print("⚠️ TRIVIA DIRECTOR: Not enough clips for Clip_Vibe_Check")
                    continue
                clip = random.choice(clips)
                correct_answer = None
                is_json_response = True
                print(f"✅ TRIVIA DIRECTOR: Got clip '{clip['trigger']}' for Clip_Vibe_Check")

                category_prompt = f\"\"\"Write one multiple-choice trivia question for fans of Captain Jonesy's gaming channel.
Jonesy uses she/her pronouns.

REAL CLIP DATA:
Game: {clip['game_title']}
Emotion Displayed: {clip['emotion_category']}
Context: {clip['lore_summary']}

Create a "Vibe Check" question that asks which game generated this specific emotion, or which emotion was generated by this specific game event.
Provide 3 believable but incorrect decoy options.
Return strictly as JSON: {{"question_text": "...", "correct_answer": "...", "decoy_1": "...", "decoy_2": "...", "decoy_3": "...", "explanation": "Brief explanation."}}\"\"\"
                selected_category = cat

            elif cat == 'Clip_Cause_And_Effect':
                clips = current_db.trivia.get_random_clip_lore(limit=10, required_fields=['trigger', 'reaction', 'characters_involved'])
                if not clips:
                    print("⚠️ TRIVIA DIRECTOR: Not enough clips for Clip_Cause_And_Effect")
                    continue
                clip = random.choice(clips)
                correct_answer = None
                is_json_response = True
                print(f"✅ TRIVIA DIRECTOR: Got clip '{clip['trigger']}' for Clip_Cause_And_Effect")

                category_prompt = f\"\"\"Write one multiple-choice trivia question for fans of Captain Jonesy's gaming channel.
Jonesy uses she/her pronouns.

REAL CLIP DATA:
Game: {clip['game_title']}
Characters Involved: {clip['characters_involved']}
Trigger (The Cause): {clip['trigger']}
Jonesy's Reaction (The Effect): {clip['reaction']}

Create a "Cause and Effect" question linking what happened to how she reacted, or vice versa.
Example: "What caused Jonesy to [Reaction] in {clip['game_title']}?" or "How did Jonesy react when [Trigger]?"
Provide 3 believable but incorrect decoy options.
Return strictly as JSON: {{"question_text": "...", "correct_answer": "...", "decoy_1": "...", "decoy_2": "...", "decoy_3": "...", "explanation": "Brief explanation."}}\"\"\"
                selected_category = cat

            elif cat == 'Franchise_Lore':"""

content = franchise_lore_pattern.sub(clip_logic, content)

# 3. Update CATEGORY_TEMPERATURES for clip types
temp_pattern = re.compile(r"                CATEGORY_TEMPERATURES = \{\n                    'Franchise_Lore': 0\.9,\n                \}")
new_temps = """                CATEGORY_TEMPERATURES = {
                    'Franchise_Lore': 0.9,
                    'Clip_Famous_Last_Words': 0.8,
                    'Clip_Vibe_Check': 0.8,
                    'Clip_Cause_And_Effect': 0.8,
                }"""
content = temp_pattern.sub(new_temps, content)

with open(r'bot\handlers\trivia\generator.py', 'w', encoding='utf-8') as f:
    f.write(content)

print("Patch applied for generator.py")
