UPDATE played_games SET canonical_name = 'Little Misfortune', alternative_names = '[]', first_played_date = '2020-12-15' WHERE id = 61;
UPDATE played_games SET canonical_name = 'Hellblade: Senua''s Sacrifice', alternative_names = '["Hellblade"]', first_played_date = '2020-12-28' WHERE id = 60;
UPDATE played_games SET canonical_name = 'Layers of Fear 2', alternative_names = '[]', first_played_date = '2021-01-12' WHERE id = 59;
UPDATE played_games SET canonical_name = 'The Medium', alternative_names = '[]', first_played_date = '2021-02-02' WHERE id = 57;
UPDATE played_games SET canonical_name = 'Assassin''s Creed Valhalla', alternative_names = '["AC Valhalla"]', first_played_date = '2021-02-16' WHERE id = 56;
UPDATE played_games SET canonical_name = 'Blair Witch', alternative_names = '[]', first_played_date = '2021-02-23' WHERE id = 55;
UPDATE played_games SET canonical_name = 'Fallout: New Vegas', alternative_names = '["FNV", "NV", "New Vegas"]', first_played_date = '2021-03-19' WHERE id = 53;
UPDATE played_games SET canonical_name = 'The Beast Inside', alternative_names = '[]', first_played_date = '2021-03-25' WHERE id = 52;
UPDATE played_games SET canonical_name = 'Red Dead Redemption 2', alternative_names = '["RDR2"]', first_played_date = '2021-04-03' WHERE id = 51;
UPDATE played_games SET canonical_name = 'God of War', alternative_names = '["Dad of War", "GOW", "God of War 2018"]', first_played_date = '2021-06-28' WHERE id = 1;
UPDATE played_games SET canonical_name = 'Resident Evil 7: Biohazard', alternative_names = '["RE7"]', first_played_date = '2021-07-29' WHERE id = 49;
UPDATE played_games SET canonical_name = 'Spider-Man 2', alternative_names = '[]', first_played_date = '2021-08-21' WHERE id = 25;
UPDATE played_games SET canonical_name = 'The Last of Us', alternative_names = '["TLOU"]', first_played_date = '2021-08-28' WHERE id = 33;
UPDATE played_games SET canonical_name = 'Bloodborne', alternative_names = '["BB"]', first_played_date = '2021-09-29' WHERE id = 48;
UPDATE played_games SET canonical_name = 'Far Cry 6', alternative_names = '[]', first_played_date = '2021-10-09' WHERE id = 47;
UPDATE played_games SET canonical_name = 'Red Dead Redemption', alternative_names = '["RDR1"]', first_played_date = '2021-11-15' WHERE id = 46;
UPDATE played_games SET canonical_name = 'Uncharted: Drake''s Fortune', alternative_names = '["Uncharted 1"]', first_played_date = '2022-01-24' WHERE id = 45;
UPDATE played_games SET canonical_name = 'Uncharted 2: Among Thieves', alternative_names = '["Uncharted 2"]', first_played_date = '2022-02-15' WHERE id = 44;
UPDATE played_games SET canonical_name = 'God of War III', alternative_names = '["GoW 3"]', first_played_date = '2022-03-09' WHERE id = 41;
UPDATE played_games SET canonical_name = 'Uncharted 3: Drake''s Deception', alternative_names = '["Uncharted 3"]', first_played_date = '2022-03-29' WHERE id = 43;
UPDATE played_games SET canonical_name = 'Uncharted 4: A Thief''s End', alternative_names = '["Uncharted 4"]', first_played_date = '2022-04-13' WHERE id = 42;
UPDATE played_games SET canonical_name = 'God of War II', alternative_names = '["GoW 2"]', first_played_date = '2022-04-18' WHERE id = 101;
UPDATE played_games SET canonical_name = 'Uncharted: The Lost Legacy', alternative_names = '["Lost Legacy"]', first_played_date = '2022-06-02' WHERE id = 40;
UPDATE played_games SET canonical_name = 'Ghost of Tsushima', alternative_names = '["GoT"]', first_played_date = '2022-06-19' WHERE id = 39;
UPDATE played_games SET canonical_name = 'Dead Space 2', alternative_names = '[]', first_played_date = '2022-07-09' WHERE id = 36;
UPDATE played_games SET canonical_name = 'Grand Theft Auto V', alternative_names = '["GTA 5"]', first_played_date = '2022-08-10' WHERE id = 38;
UPDATE played_games SET canonical_name = 'Alien: Isolation', alternative_names = '[]', first_played_date = '2022-10-13' WHERE id = 37;
UPDATE played_games SET canonical_name = 'God of War Ragnarök', alternative_names = '["GoW Ragnarok"]', first_played_date = '2022-11-09' WHERE id = 35;
UPDATE played_games SET canonical_name = 'The Callisto Protocol', alternative_names = '[]', first_played_date = '2022-12-05' WHERE id = 34;
UPDATE played_games SET canonical_name = 'Dead Space', alternative_names = '[]', first_played_date = '2023-01-29' WHERE id = 32;
UPDATE played_games SET canonical_name = 'Grand Theft Auto IV', alternative_names = '["GTA 4"]', first_played_date = '2023-03-02' WHERE id = 31;
UPDATE played_games SET canonical_name = 'Batman: Arkham Asylum', alternative_names = '["Batman AA"]', first_played_date = '2023-05-14' WHERE id = 30;
UPDATE played_games SET canonical_name = 'Grand Theft Auto IV: The Lost and Damned', alternative_names = '["TLAD"]', first_played_date = '2023-06-01' WHERE id = 29;
UPDATE played_games SET canonical_name = 'Batman: Arkham Knight', alternative_names = '[]', first_played_date = '2023-07-06' WHERE id = 27;
UPDATE played_games SET canonical_name = 'Batman: Arkham City', alternative_names = '[]', first_played_date = '2023-07-06' WHERE id = 81;
UPDATE played_games SET canonical_name = 'Grand Theft Auto IV: The Ballad of Gay Tony', alternative_names = '["TBoGT"]', first_played_date = '2023-07-09' WHERE id = 28;
UPDATE played_games SET canonical_name = 'Mafia II', alternative_names = '["Mafia 2"]', first_played_date = '2023-08-24' WHERE id = 24;
UPDATE played_games SET canonical_name = 'Outlast', alternative_names = '["Outlast 1"]', first_played_date = '2023-10-01' WHERE id = 26;
UPDATE played_games SET canonical_name = 'Call of Duty: Modern Warfare 3', alternative_names = '["MW3"]', first_played_date = '2024-01-01' WHERE id = 23;
UPDATE played_games SET canonical_name = 'Call of Duty: World at War', alternative_names = '["WaW"]', first_played_date = '2024-02-22' WHERE id = 22;
UPDATE played_games SET canonical_name = 'Call of Duty: Black Ops II', alternative_names = '["BO2"]', first_played_date = '2024-03-10' WHERE id = 21;
UPDATE played_games SET canonical_name = 'Elden Ring', alternative_names = '["ER"]', first_played_date = '2024-04-14' WHERE id = 20;
UPDATE played_games SET canonical_name = 'Halo: Combat Evolved', alternative_names = '["Halo 1", "Halo CE"]', first_played_date = '2024-05-01' WHERE id = 19;
UPDATE played_games SET canonical_name = 'Halo 2', alternative_names = '["H2"]', first_played_date = '2024-05-30' WHERE id = 18;
UPDATE played_games SET canonical_name = 'Halo 3', alternative_names = '["H3"]', first_played_date = '2024-07-09' WHERE id = 17;
UPDATE played_games SET canonical_name = 'Gears of War', alternative_names = '[]', first_played_date = '2024-07-30' WHERE id = 16;
UPDATE played_games SET canonical_name = 'Gears of War 4', alternative_names = '["Gears 4"]', first_played_date = '2024-08-22' WHERE id = 10;
UPDATE played_games SET canonical_name = 'Silent Hill 2', alternative_names = '["SH2"]', first_played_date = '2024-10-28' WHERE id = 15;
UPDATE played_games SET canonical_name = 'Batman: Arkham Origins', alternative_names = '[]', first_played_date = '2024-12-05' WHERE id = 14;
UPDATE played_games SET canonical_name = 'Wolfenstein: The New Order', alternative_names = '[]', first_played_date = '2025-01-09' WHERE id = 13;
UPDATE played_games SET canonical_name = 'Grand Theft Auto: San Andreas', alternative_names = '["GTA SA"]', first_played_date = '2025-02-06' WHERE id = 12;
UPDATE played_games SET canonical_name = 'The Walking Dead', alternative_names = '["TWD"]', first_played_date = '2025-04-17' WHERE id = 11;
UPDATE played_games SET canonical_name = 'Until Dawn', alternative_names = '[]', first_played_date = '2025-07-03' WHERE id = 8;
UPDATE played_games SET canonical_name = 'The Evil Within', alternative_names = '[]', first_played_date = '2025-08-14' WHERE id = 7;
UPDATE played_games SET canonical_name = 'Resident Evil Village', alternative_names = '["RE8"]', first_played_date = '2025-09-08' WHERE id = 119;
UPDATE played_games SET canonical_name = 'Cronos: The New Dawn', alternative_names = '[]', first_played_date = '2025-09-10' WHERE id = 110;
UPDATE played_games SET canonical_name = 'Silent Hill f', alternative_names = '[]', first_played_date = '2025-09-23' WHERE id = 114;
UPDATE played_games SET canonical_name = 'Sleeping Dogs', alternative_names = '[]', first_played_date = '2025-10-23' WHERE id = 74;
UPDATE played_games SET canonical_name = 'Ghost of Yotei', alternative_names = '[]', first_played_date = '2025-10-29' WHERE id = 111;
UPDATE played_games SET canonical_name = 'Saints Row 2', alternative_names = '[]', first_played_date = '2025-11-03' WHERE id = 122;
UPDATE played_games SET canonical_name = 'Thank Goodness You''re Here!', alternative_names = '[]', first_played_date = '2025-12-01' WHERE id = 127;
UPDATE played_games SET canonical_name = 'Sleep Awake', alternative_names = '[]', first_played_date = '2025-12-03' WHERE id = 126;
UPDATE played_games SET canonical_name = 'Mafia: The Old Country', alternative_names = '[]', first_played_date = '2025-12-05' WHERE id = 125;
UPDATE played_games SET canonical_name = 'Star Wars Jedi: Fallen Order', alternative_names = '["Fallen Order"]', first_played_date = '2025-12-19' WHERE id = 128;