import asyncio
import sys
import os
import json

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
# pyrefly: ignore [missing-import]
from bot.database import get_database

def main():
    db = get_database()
    conn = db.get_connection()
    try:
        with conn.cursor() as cur:
            # My most recent entry (Hitman 3 duck)
            cur.execute("""
                SELECT game_title, reaction, trigger, lore_summary, notable_quote, 
                       emotion_category, characters_involved, clip_outcome 
                FROM clip_lore 
                WHERE canonical_url = 'https://clips.twitch.tv/antsygiantlarkpicomause-xm0opnh5hidl6qia'
            """)
            my_clip = cur.fetchone()
            
            # An older entry generated by the bot natively
            cur.execute("""
                SELECT game_title, reaction, trigger, lore_summary, notable_quote, 
                       emotion_category, characters_involved, clip_outcome 
                FROM clip_lore 
                WHERE canonical_url != 'https://clips.twitch.tv/antsygiantlarkpicomause-xm0opnh5hidl6qia'
                AND canonical_url != 'https://clips.twitch.tv/popularfaithfulferretpetezarolltie-tupwjbyndlznvg5p'
                AND canonical_url != 'https://clips.twitch.tv/heartlesscreduloustrayminglee-jngb1ztdi8li05-v'
                AND canonical_url != 'https://clips.twitch.tv/correctreliablecaterpillardogface-bhuswenz75pt5d_x'
                AND canonical_url != 'https://clips.twitch.tv/puzzledquaintsamosamikehogu-dydulht3oc1zfqfg'
                AND canonical_url != 'https://clips.twitch.tv/alluringprecioushamsterkappaclaus-pidgcrdt88v3uiuz'
                LIMIT 1
            """)
            bot_clip = cur.fetchone()
            
            print("--- ANTIGRAVITY GENERATED TRIVIA ---")
            print(json.dumps(dict(my_clip), indent=2))
            print("\n--- HISTORICAL BOT GENERATED TRIVIA ---")
            print(json.dumps(dict(bot_clip), indent=2))
                
    except Exception as e:
        print(f"Error querying database: {e}")
    finally:
        conn.close()

if __name__ == "__main__":
    main()
